/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.forms;

import estoque.CepService;
import estoque.Cliente;
import estoque.IOModelInterface;
import estoque.util;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;
import java.util.Date;

/**
 *
 * @author gilmar
 */
public class jPanelClientes extends javax.swing.JPanel {

    /**
     * Creates new form jPanelProdutos
     */
    public jPanelClientes() {
        initComponents();
        this.loadItems();
    }
    
    /**
     * Carrega todos os clientes na tabela
     */
    public void loadItems(){
        Cliente cli = new Cliente();
        
        TableModel model = cli.getTableModel() ;
        this.tableClientes.setModel(model);
        this.tableClientes.setAutoCreateRowSorter(true);
        this.tableClientes.enableInputMethods(false);
        this.jTextFile.setText( String.format( "Dados extraidos do arquivo: %s" , cli.getFileName()) );
    }
    
    public void addCliente() {
        while (true) {
            try {
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                long codigo = (long) Integer.parseInt(util.showInput("Digite o código do cliente.")) ;
                String nome = util.showInput("Digite o nome.");
                String sobrenome = util.showInput("Digite o sobrenome.");
                Long cpf = Long.parseLong(util.showInput("Digite o CPF."));
                String cep = util.showInput("Digite o Código Postal.");
                Integer numero = Integer.parseInt(util.showInput("Digite o número da residência."));
                CepService cws = new CepService(cep);
                Cliente cli = new Cliente();
                cli.fillFromService(cws);
                cli.setCEP(Long.parseLong(cep));
                cli.setNumero(numero);
                
                String message = String.format( "O endereço abaixo está correto?\n%s", cli.getEndereco());
                if(util.showConfirm(message, "Confirmação de endereço") == false){
                    String logradouro = util.showInput("Digite o logradouro.");
                    String bairro = util.showInput("Digite o bairro.");
                    String cidade = util.showInput("Digite a cidade.");
                    String estado = util.showInput("Digite o estado.");
                    cli.setLogadouro(logradouro);
                    cli.setBairro(bairro);
                    cli.setCidade(cidade);
                    cli.setEstado(estado);
                }
                
                Date nascimento = formatter.parse(util.showInput("Digite a data de Nascimento."));
                String email = util.showInput("Digite o email.");
                String telefone = util.showInput("Digite o telefone.");

                cli.setCodigo(codigo);
                cli.setDataNascimento(nascimento);
                cli.setEmail(email);
                cli.setNome(nome);
                cli.setSobrenome(sobrenome);
                cli.setCPF(cpf);
                cli.setTelefone(telefone);
                
                cli.save();
                this.loadItems();
                
                util.showMessage("Cliente salvo com sucesso");
                if ( util.showConfirm( "Gostaria de cadastrar mais um cliente?" , "Cliente") == false ) {
                    break;
                }
            } catch (Exception e) {
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFile = new javax.swing.JTextPane();
        btnLoadFile = new javax.swing.JButton();
        btnOdernar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        tableClientes.setAutoCreateRowSorter(true);
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableClientes.setName(""); // NOI18N
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableClientesMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableClientes);

        btnAdd.setText("Adicionar");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });

        btnDelete.setText("Excluir");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBusca.setText("Localizar");
        btnBusca.setToolTipText("");
        btnBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuscaMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Clientes");

        jTextFile.setBackground(new java.awt.Color(254, 240, 156));
        jTextFile.setText("Dados oriundos do arquivo:");
        jScrollPane1.setViewportView(jTextFile);

        btnLoadFile.setToolTipText("");
        btnLoadFile.setLabel("Carregar arquivo...");
        btnLoadFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoadFileMouseReleased(evt);
            }
        });

        btnOdernar.setToolTipText("");
        btnOdernar.setLabel("Odernar");
        btnOdernar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOdernarMouseReleased(evt);
            }
        });
        btnOdernar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdernarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(6, 6, 6)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdernar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLoadFile)))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnBusca)
                        .addComponent(btnOdernar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLoadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18))
        );

        btnLoadFile.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscaMouseReleased
    }//GEN-LAST:event_btnBuscaMouseReleased

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        this.addCliente();
    }//GEN-LAST:event_btnAddMouseReleased

    private void btnLoadFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadFileMouseReleased
        JFileChooser chooser = new JFileChooser();
        int status = chooser.showSaveDialog(null);
        if (status == JFileChooser.APPROVE_OPTION) {
            File outfile = chooser.getSelectedFile();
             this.jTextFile.setText( String.format( "Dados extraidos do arquivo: %s" , outfile.getPath()) );
        }
    }//GEN-LAST:event_btnLoadFileMouseReleased

    private void btnOdernarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOdernarMouseReleased
        TableModel model = this.tableClientes.getModel();
        this.tableClientes.getSelectedRow();
    }//GEN-LAST:event_btnOdernarMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = this.tableClientes.getSelectedRow();
                
        if(row == -1){
            util.showMessage("Selecione um cliente para excluir.");
            return;
        }
       
        long ID = (long) this.tableClientes.getModel().getValueAt(row, 0);
        String item = (String) this.tableClientes.getModel().getValueAt(row, 1);
        String message = String.format("Tem certeza que deseja excluir o cliente '%s'?",item);
        if(util.showConfirm(message, "Remover cliente?")) {
           IOModelInterface cli = new Cliente();
            try {
                cli.remove(ID);
            } catch (IOException ex) {
                Logger.getLogger(jPanelClientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jPanelClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
           this.loadItems();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnOdernarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdernarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOdernarActionPerformed

    private void tableClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseReleased
        int row = this.tableClientes.getSelectedRow();
        long ID = (long) this.tableClientes.getModel().getValueAt(row, 0);
        String item = (String) this.tableClientes.getModel().getValueAt(row, 1);
        Cliente cli = new Cliente();
        try {
            Cliente c = (Cliente) cli.findByID(ID);
        } catch (IOException ex) {
            Logger.getLogger(jPanelClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableClientesMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnOdernar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextFile;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
