/*
 * Tela de vendas
 */
package estoque.forms;

import estoque.CepService;
import estoque.Cliente;
import estoque.IOModelInterface;
import estoque.util;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;
import java.util.Date;

/**
 *
 * @author gilmar
 */
public class jPanelVendas extends javax.swing.JPanel {

    /**
     * Creates new form jPanelProdutos
     */
    public jPanelVendas() {
        initComponents();
        this.loadItems();
    }
    
    /**
     * Carrega todos os clientes na tabela
     */
    public void loadItems(){
    }
    
    public void addProduto() {
        while (true) {
            try {
                Cliente cli = new Cliente();
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                
                long codigo = (long) Integer.parseInt(util.showInput("Digite o código do cliente.")) ;
                String nome = util.showInput("Digite o nome.");
                String sobrenome = util.showInput("Digite o sobrenome.");
                Long cpf = Long.parseLong(util.showInput("Digite o CPF."));
                String cep = util.showInput("Digite o Código Postal.");
                String sexo = util.showOptions("Selecione o sexo.", cli.getMapSexo(), "Sexo").toString();
                Integer numero = Integer.parseInt(util.showInput("Digite o número da residência."));
                CepService cws = new CepService(cep);
                cli.fillFromService(cws);
                cli.setCEP(Long.parseLong(cep));
                cli.setNumero(numero);
                cli.setSexo(sexo);
                
                
                String message = String.format( "O endereço abaixo está correto?\n%s", cli.getEndereco());
                if(util.showConfirm(message, "Confirmação de endereço") == false){
                    String logradouro = util.showInput("Digite o logradouro.");
                    String bairro = util.showInput("Digite o bairro.");
                    String cidade = util.showInput("Digite a cidade.");
                    String estado = util.showInput("Digite o estado.");
                    cli.setLogadouro(logradouro);
                    cli.setBairro(bairro);
                    cli.setCidade(cidade);
                    cli.setEstado(estado);
                }
                
                Date nascimento = formatter.parse(util.showInput("Digite a data de Nascimento."));
                String email = util.showInput("Digite o email.");
                String telefone = util.showInput("Digite o telefone.");

                cli.setCodigo(codigo);
                cli.setDataNascimento(nascimento);
                cli.setEmail(email);
                cli.setNome(nome);
                cli.setSobrenome(sobrenome);
                cli.setCPF(cpf);
                cli.setTelefone(telefone);
                
                cli.save();
                this.loadItems();
                
                util.showMessage("Cliente salvo com sucesso");
                if ( util.showConfirm( "Gostaria de cadastrar mais um cliente?" , "Cliente") == false ) {
                    break;
                }
            } catch (Exception e) {
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLoadFile = new javax.swing.JButton();
        jPanelDetalhes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        btnLoadFile1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        tableItems.setAutoCreateRowSorter(true);
        tableItems.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Valor unitário", "Quantidade", "Subtotal"
            }
        ));
        tableItems.setName(""); // NOI18N
        tableItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableItemsMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableItems);
        if (tableItems.getColumnModel().getColumnCount() > 0) {
            tableItems.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        btnAdd.setMnemonic('n');
        btnAdd.setText("Nova venda");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });

        btnDelete.setMnemonic('x');
        btnDelete.setText("Excluir item");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBusca.setMnemonic('l');
        btnBusca.setText("Localizar");
        btnBusca.setToolTipText("");
        btnBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuscaMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle de Vendas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLoadFile.setText("Carregar venda...");
        btnLoadFile.setToolTipText("");
        btnLoadFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoadFileMouseReleased(evt);
            }
        });
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFileActionPerformed(evt);
            }
        });

        jPanelDetalhes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Endereço de entrega:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelEndereco.setText("-");
        jLabelEndereco.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelNome.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelNome.setText("Nome do cliente");

        jLabelCPF.setText("CPF");

        jLabelEmail.setText("E-mail");

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estoque/forms/icon-venda.png"))); // NOI18N

        javax.swing.GroupLayout jPanelDetalhesLayout = new javax.swing.GroupLayout(jPanelDetalhes);
        jPanelDetalhes.setLayout(jPanelDetalhesLayout);
        jPanelDetalhesLayout.setHorizontalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelDetalhesLayout.setVerticalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetalhesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmail))
                    .addComponent(jLabelIcon))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTotal.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("Total: R$ 0,00");

        btnLoadFile1.setMnemonic('e');
        btnLoadFile1.setText("Alterar endereço de entrega");
        btnLoadFile1.setToolTipText("");
        btnLoadFile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoadFile1MouseReleased(evt);
            }
        });
        btnLoadFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFile1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addComponent(jPanelDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(6, 6, 6)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLoadFile1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jPanelDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTotal)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdd)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnBusca)
                            .addComponent(btnLoadFile)
                            .addComponent(btnLoadFile1))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnLoadFile.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscaMouseReleased
    }//GEN-LAST:event_btnBuscaMouseReleased

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        this.addProduto();
    }//GEN-LAST:event_btnAddMouseReleased

    private void btnLoadFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadFileMouseReleased
        JFileChooser chooser = new JFileChooser();
        int status = chooser.showSaveDialog(null);
        if (status == JFileChooser.APPROVE_OPTION) {
            File outfile = chooser.getSelectedFile();
        }
    }//GEN-LAST:event_btnLoadFileMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = this.tableItems.getSelectedRow();
                
        if(row == -1){
            util.showMessage("Selecione um cliente para excluir.");
            return;
        }
       
        long ID = (long) this.tableItems.getModel().getValueAt(row, 0);
        String item = (String) this.tableItems.getModel().getValueAt(row, 1);
        String message = String.format("Tem certeza que deseja excluir o cliente '%s'?",item);
        if(util.showConfirm(message, "Remover cliente?")) {
           IOModelInterface cli = new Cliente();
            try {
                cli.remove(ID);
            } catch (IOException ex) {
                Logger.getLogger(jPanelVendas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jPanelVendas.class.getName()).log(Level.SEVERE, null, ex);
            }
           this.loadItems();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void fillCliente(){
        int row = this.tableItems.getSelectedRow();
        long ID = (long) this.tableItems.getModel().getValueAt(row, 0);
        String item = (String) this.tableItems.getModel().getValueAt(row, 1);
        Cliente cli = new Cliente();
        try {
            Cliente c = (Cliente) cli.findByID(ID);
            this.jLabelCPF.setText("CPF: " + c.getFormatCPF());
            this.jLabelNome.setText(c.getFullName());
            this.jLabelEmail.setText("E-mail: " + c.getEmail());
            this.jLabelEndereco.setText(c.getEndereco());
        } catch (IOException ex) {
            Logger.getLogger(jPanelVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tableItemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItemsMouseReleased
        
    }//GEN-LAST:event_tableItemsMouseReleased

    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void btnLoadFile1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadFile1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadFile1MouseReleased

    private void btnLoadFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadFile1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnLoadFile1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelDetalhes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableItems;
    // End of variables declaration//GEN-END:variables
}
