/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque.forms;

import estoque.Categoria;
import estoque.IOModelInterface;
import estoque.Produto;
import estoque.util;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author gilmar
 */
public final class jPanelProdutos extends javax.swing.JPanel {

    /**
     * Creates new form jPanelProdutos
     */
    public jPanelProdutos() {
        initComponents();
        this.loadItems();
    }
    
    public void loadItems(){
        Produto prod = new Produto();
        
        TableModel model = prod.getTableModel() ;
        this.tableProdutos.setModel(model);
        this.tableProdutos.setAutoCreateRowSorter(true);
        this.tableProdutos.enableInputMethods(false);
        this.jTextFile.setText( String.format("Dados extraidos do arquivo: %s" , prod.getFileName()));
    }
    
    public void novoProduto() {
        while (true) {
            try {
                Categoria cat = new Categoria();
                List objs = cat.getAll();
                
                if( objs.isEmpty() ) {
                    util.showMessage(
                        "Não há categoria de produto cadastrado.\n" +
                        "Cadastre as categorias desejadas antes de continuar.",
                        JOptionPane.WARNING_MESSAGE
                    );
                    
                    return ;
                }
                
                long codigo = (long) Integer.parseInt(util.showInput("Digite o código do produto.")) ;
                Categoria categoria = (Categoria) util.showOptions("Selecione a categoria.", objs.toArray(), "Categoria") ;
                String nome = util.showInput("Digite o nome.");
                String descricao = util.showInput("Digite a descrição.");
                double peso = Double.parseDouble(util.showInput("Digite o peso (kg).")) ;
                double valor = Double.parseDouble(util.showInput("Digite o valor unitário.")) ;
                int estoque = Integer.parseInt(util.showInput("Digite a quantidade em estoque.")) ;

                estoque.Produto produto = new Produto(nome, descricao, valor);
                produto.setCodigo(codigo);
                produto.setCodCategoria(categoria);
                produto.setPeso(peso);
                produto.setSaldoEstoque(estoque);
                produto.save();
                this.loadItems();
                
                util.showMessage("Produto salvo com sucesso");
                if ( util.showConfirm( "Gostaria de cadastrar mais um novo produto?" , "Estoque") == false ) {
                    break;
                }
            } catch (Exception e) {
                util.showMessage("Valor inválido informado!", JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        btnAddProduto = new javax.swing.JButton();
        btnDelProduto = new javax.swing.JButton();
        btnBuscaProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFile = new javax.swing.JTextPane();
        btnLoadFile = new javax.swing.JButton();
        btnOdernar = new javax.swing.JButton();
        jPanelDetalhes2 = new javax.swing.JPanel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelEstoque = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        btnAddCategoria = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        tableProdutos.setAutoCreateRowSorter(true);
        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProdutos.setName(""); // NOI18N
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableProdutosMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableProdutos);

        btnAddProduto.setMnemonic('a');
        btnAddProduto.setText("Adicionar");
        btnAddProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddProdutoMouseReleased(evt);
            }
        });
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        btnDelProduto.setMnemonic('x');
        btnDelProduto.setText("Excluir");
        btnDelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelProdutoActionPerformed(evt);
            }
        });

        btnBuscaProduto.setMnemonic('l');
        btnBuscaProduto.setText("Localizar");
        btnBuscaProduto.setToolTipText("");
        btnBuscaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuscaProdutoMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de produtos");

        jTextFile.setBackground(new java.awt.Color(254, 240, 156));
        jTextFile.setText("Dados oriundos do arquivo:");
        jScrollPane1.setViewportView(jTextFile);

        btnLoadFile.setToolTipText("");
        btnLoadFile.setLabel("Carregar arquivo...");
        btnLoadFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoadFileMouseReleased(evt);
            }
        });

        btnOdernar.setMnemonic('o');
        btnOdernar.setToolTipText("");
        btnOdernar.setLabel("Odernar");
        btnOdernar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOdernarMouseReleased(evt);
            }
        });
        btnOdernar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdernarActionPerformed(evt);
            }
        });

        jPanelDetalhes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDescricao.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelDescricao.setText("Produto");

        jLabelEstoque.setText("Estoque: 0");

        jLabelPreco.setText("Valor:");

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estoque/forms/produto-icon2.png"))); // NOI18N

        jLabelCategoria.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCategoria.setText("Sessão");

        javax.swing.GroupLayout jPanelDetalhes2Layout = new javax.swing.GroupLayout(jPanelDetalhes2);
        jPanelDetalhes2.setLayout(jPanelDetalhes2Layout);
        jPanelDetalhes2Layout.setHorizontalGroup(
            jPanelDetalhes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetalhes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetalhes2Layout.createSequentialGroup()
                        .addGroup(jPanelDetalhes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 199, Short.MAX_VALUE))
                    .addGroup(jPanelDetalhes2Layout.createSequentialGroup()
                        .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDetalhes2Layout.setVerticalGroup(
            jPanelDetalhes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetalhes2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetalhes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetalhes2Layout.createSequentialGroup()
                        .addGroup(jPanelDetalhes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescricao)
                            .addComponent(jLabelCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPreco))
                    .addComponent(jLabelIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddCategoria.setMnemonic('c');
        btnAddCategoria.setText("Categoria...");
        btnAddCategoria.setToolTipText("");
        btnAddCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddCategoriaMouseReleased(evt);
            }
        });
        btnAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLoadFile))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jPanelDetalhes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscaProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdernar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddCategoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelProduto)
                    .addComponent(btnBuscaProduto)
                    .addComponent(btnOdernar)
                    .addComponent(btnAddProduto)
                    .addComponent(btnAddCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanelDetalhes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLoadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18))
        );

        btnLoadFile.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscaProdutoMouseReleased
    }//GEN-LAST:event_btnBuscaProdutoMouseReleased

    private void btnAddProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProdutoMouseReleased
        this.novoProduto();
    }//GEN-LAST:event_btnAddProdutoMouseReleased

    private void btnLoadFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadFileMouseReleased
        JFileChooser chooser = new JFileChooser();
        int status = chooser.showSaveDialog(null);
        if (status == JFileChooser.APPROVE_OPTION) {
            File outfile = chooser.getSelectedFile();
             this.jTextFile.setText( String.format( "Dados extraidos do arquivo: %s" , outfile.getPath()) );
        }
    }//GEN-LAST:event_btnLoadFileMouseReleased

    private void btnOdernarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOdernarMouseReleased
        TableModel model = this.tableProdutos.getModel();
        this.tableProdutos.getSelectedRow();
    }//GEN-LAST:event_btnOdernarMouseReleased

    private void btnDelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProdutoActionPerformed
        int row = this.tableProdutos.getSelectedRow();
                
        if(row == -1){
            util.showMessage("Selecione um item para excluir.");
            return;
        }
       
        long ID = (long) this.tableProdutos.getModel().getValueAt(row, 0);
        String item = (String) this.tableProdutos.getModel().getValueAt(row, 1);
        String message = String.format("Tem certeza que deseja excluir o item '%s'?",item);
       if(util.showConfirm(message, "Remover item?")) {
           IOModelInterface produto = new Produto();
            try {
                produto.remove(ID);
            } catch (IOException ex) {
                Logger.getLogger(jPanelProdutos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jPanelProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
           this.loadItems();
       }
    }//GEN-LAST:event_btnDelProdutoActionPerformed

    private void btnOdernarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdernarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOdernarActionPerformed

    private void tableProdutosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseReleased
        int row = this.tableProdutos.getSelectedRow();
        long ID = (long) this.tableProdutos.getModel().getValueAt(row, 0);
        Produto prod = new Produto();
        
        try {
            Produto p = (Produto) prod.findByID(ID);
            String estoque = Integer.toString(p.getSaldoEstoque());
            this.jLabelDescricao.setText(String.format("%s %s", p.getNome(), p.getDescricao()));
            this.jLabelEstoque.setText(String.format("Saldo em estoque: %s", estoque));
            this.jLabelPreco.setText(p.getFormatPrice());
            this.jLabelCategoria.setText(p.getCategoria().toString());
        } catch (IOException ex) {
            Logger.getLogger(jPanelClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableProdutosMouseReleased

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnAddCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCategoriaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCategoriaMouseReleased

    private void btnAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoriaActionPerformed
       MainScreen main = new MainScreen();
       main.showCategoria();
    }//GEN-LAST:event_btnAddCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoria;
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnBuscaProduto;
    private javax.swing.JButton btnDelProduto;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnOdernar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEstoque;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JPanel jPanelDetalhes2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextFile;
    private javax.swing.JTable tableProdutos;
    // End of variables declaration//GEN-END:variables
}
