/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CategoriaController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Categoria;
import model.Util;

/**
 *
 * @author gilmar
 */
public final class jPanelCategorias extends javax.swing.JPanel {
    
    private CategoriaController controller ;

    /**
     * Creates new form jPanelProdutos
     */
    public jPanelCategorias() {
        this.controller = new CategoriaController();
        initComponents();
        this.loadItems();
    }
    
    public void loadItems(){
        TableModel model = this.controller.getTableModel() ;
        this.tableCategoria.setModel(model);
        this.tableCategoria.setAutoCreateRowSorter(true);
        this.tableCategoria.enableInputMethods(false);
        this.lblSource.setText(String.format("Arquivo: %s" , this.controller.getObjModel().getFileName()));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableCategoria = new javax.swing.JTable();
        btnAddCategoria = new javax.swing.JButton();
        btnDelCategoria = new javax.swing.JButton();
        btnBuscaCategoria = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        btnLoadFile = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        btnSaveToFile = new javax.swing.JButton();
        lblSource = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(560, 480));

        tableCategoria.setAutoCreateRowSorter(true);
        tableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCategoria.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableCategoria.setName(""); // NOI18N
        jScrollPane2.setViewportView(tableCategoria);

        btnAddCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/add.png"))); // NOI18N
        btnAddCategoria.setMnemonic('n');
        btnAddCategoria.setText("Novo");
        btnAddCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddCategoriaMouseReleased(evt);
            }
        });
        btnAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoriaActionPerformed(evt);
            }
        });

        btnDelCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/delete.png"))); // NOI18N
        btnDelCategoria.setMnemonic('x');
        btnDelCategoria.setText("Excluir");
        btnDelCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCategoriaActionPerformed(evt);
            }
        });

        btnBuscaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search.png"))); // NOI18N
        btnBuscaCategoria.setMnemonic('l');
        btnBuscaCategoria.setText("Localizar");
        btnBuscaCategoria.setToolTipText("");
        btnBuscaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuscaCategoriaMouseReleased(evt);
            }
        });
        btnBuscaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCategoriaActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Categoria de Produtos");

        btnLoadFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/load-from-file.png"))); // NOI18N
        btnLoadFile.setMnemonic('c');
        btnLoadFile.setText("Carregar do arquivo...");
        btnLoadFile.setToolTipText("");
        btnLoadFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoadFileMouseReleased(evt);
            }
        });
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFileActionPerformed(evt);
            }
        });

        btnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/refresh-icon.gif"))); // NOI18N
        btnReload.setMnemonic('r');
        btnReload.setText("Recarregar");
        btnReload.setToolTipText("");
        btnReload.setAutoscrolls(true);
        btnReload.setEnabled(false);
        btnReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReloadMouseReleased(evt);
            }
        });
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        btnSaveToFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/save-on-file.png"))); // NOI18N
        btnSaveToFile.setMnemonic('s');
        btnSaveToFile.setText("Salvar em arquivo...");
        btnSaveToFile.setToolTipText("");
        btnSaveToFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSaveToFileMouseReleased(evt);
            }
        });
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });

        lblSource.setBackground(new java.awt.Color(248, 248, 193));
        lblSource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/refresh-icon.gif"))); // NOI18N
        lblSource.setText("Dados oriundos do arquivo:");
        lblSource.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 203, 111), 1, true));
        lblSource.setIconTextGap(5);
        lblSource.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReload)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLoadFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSaveToFile))
                            .addComponent(lblSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCategoria)
                    .addComponent(btnDelCategoria)
                    .addComponent(btnBuscaCategoria)
                    .addComponent(btnReload)
                    .addComponent(btnLoadFile)
                    .addComponent(btnSaveToFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSource, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        btnLoadFile.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscaCategoriaMouseReleased
    }//GEN-LAST:event_btnBuscaCategoriaMouseReleased

    private void btnAddCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCategoriaMouseReleased
        while (true) {
            try {
                if( ! this.controller.create() ){
                    break;
                }
                
                this.loadItems();
                if ( Util.showConfirm( "Gostaria de cadastrar mais uma categoria?" , "Categoria de produto") == false ) {
                    break;
                }
            } catch (Exception e) {
                break;
            }
        }
    }//GEN-LAST:event_btnAddCategoriaMouseReleased

    private void btnLoadFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadFileMouseReleased
    }//GEN-LAST:event_btnLoadFileMouseReleased

    private void btnDelCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCategoriaActionPerformed
       this.controller.remove(this.tableCategoria) ;
       this.loadItems();
    }//GEN-LAST:event_btnDelCategoriaActionPerformed

    private void btnAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCategoriaActionPerformed

    private void btnBuscaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCategoriaActionPerformed
        Categoria c = (Categoria) this.controller.search();
        
        this.btnReload.setEnabled(false);
        if ( c.hashCode() == 0 ) {
            Util.showMessage("Categoria não encontrada.", "Buscador", JOptionPane.WARNING_MESSAGE );
            return ;
        }
      
        this.btnReload.setEnabled(true);
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Código");
        model.addColumn("Nome");
        model.addColumn("Descrição");
        Object[] data = {
             c.getCodigo(),
             c.getNome(),
             c.getDescricao()
         };

        model.addRow(data);
        this.tableCategoria.setModel(model);

      
    }//GEN-LAST:event_btnBuscaCategoriaActionPerformed

    private void btnReloadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReloadMouseReleased

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        this.loadItems();
        this.btnReload.setEnabled(false);
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnSaveToFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveToFileMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveToFileMouseReleased

    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        this.controller.loadFromFile(this.lblSource);
        this.loadItems();
    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
       this.controller.saveToFile();
    }//GEN-LAST:event_btnSaveToFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoria;
    private javax.swing.JButton btnBuscaCategoria;
    private javax.swing.JButton btnDelCategoria;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSource;
    private javax.swing.JTable tableCategoria;
    // End of variables declaration//GEN-END:variables
}
