/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CategoriaController;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Categoria;
import model.Util;

/**
 *
 * @author gilmar
 */
public final class jPanelCategorias extends javax.swing.JPanel {
    
    private CategoriaController controller ;

    /**
     * Creates new form jPanelProdutos
     */
    public jPanelCategorias() {
        this.controller = new CategoriaController();
        initComponents();
        this.loadItems();
    }
    
    public void loadItems(){
        TableModel model = this.controller.getTableModel() ;
        this.tableCategoria.setModel(model);
        this.tableCategoria.setAutoCreateRowSorter(true);
        this.tableCategoria.enableInputMethods(false);
        this.jTextFile.setText(String.format("Arquivo: %s" , this.controller.getObjModel().getFileName()));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableCategoria = new javax.swing.JTable();
        btnAddCategoria = new javax.swing.JButton();
        btnDelCategoria = new javax.swing.JButton();
        btnBuscaCategoria = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFile = new javax.swing.JTextPane();
        btnLoadFile = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(560, 480));

        tableCategoria.setAutoCreateRowSorter(true);
        tableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCategoria.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableCategoria.setName(""); // NOI18N
        jScrollPane2.setViewportView(tableCategoria);

        btnAddCategoria.setMnemonic('a');
        btnAddCategoria.setText("Adicionar");
        btnAddCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddCategoriaMouseReleased(evt);
            }
        });
        btnAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoriaActionPerformed(evt);
            }
        });

        btnDelCategoria.setMnemonic('x');
        btnDelCategoria.setText("Excluir");
        btnDelCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCategoriaActionPerformed(evt);
            }
        });

        btnBuscaCategoria.setMnemonic('l');
        btnBuscaCategoria.setText("Localizar");
        btnBuscaCategoria.setToolTipText("");
        btnBuscaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuscaCategoriaMouseReleased(evt);
            }
        });
        btnBuscaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCategoriaActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Categoria de Produtos");

        jTextFile.setBackground(new java.awt.Color(254, 240, 156));
        jTextFile.setText("Dados oriundos do arquivo:");
        jScrollPane1.setViewportView(jTextFile);

        btnLoadFile.setMnemonic('c');
        btnLoadFile.setToolTipText("");
        btnLoadFile.setLabel("Carregar arquivo...");
        btnLoadFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoadFileMouseReleased(evt);
            }
        });

        btnReload.setMnemonic('r');
        btnReload.setText("Recarregar");
        btnReload.setToolTipText("");
        btnReload.setAutoscrolls(true);
        btnReload.setEnabled(false);
        btnReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReloadMouseReleased(evt);
            }
        });
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAddCategoria)
                                .addGap(6, 6, 6)
                                .addComponent(btnDelCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReload, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLoadFile))
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCategoria)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelCategoria)
                        .addComponent(btnBuscaCategoria)
                        .addComponent(btnLoadFile)
                        .addComponent(btnReload)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnLoadFile.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscaCategoriaMouseReleased
    }//GEN-LAST:event_btnBuscaCategoriaMouseReleased

    private void btnAddCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCategoriaMouseReleased
        while (true) {
            try {
                if( ! this.controller.create() ){
                    break;
                }
                
                this.loadItems();
                if ( Util.showConfirm( "Gostaria de cadastrar mais uma categoria?" , "Categoria de produto") == false ) {
                    break;
                }
            } catch (Exception e) {
                break;
            }
        }
    }//GEN-LAST:event_btnAddCategoriaMouseReleased

    private void btnLoadFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadFileMouseReleased
        JFileChooser chooser = new JFileChooser();
        int status = chooser.showSaveDialog(null);
        if (status == JFileChooser.APPROVE_OPTION) {
            File outfile = chooser.getSelectedFile();
            this.jTextFile.setText(String.format( "Dados extraidos do arquivo: %s" , outfile.getPath()));
        }
    }//GEN-LAST:event_btnLoadFileMouseReleased

    private void btnDelCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCategoriaActionPerformed
       this.controller.remove(this.tableCategoria) ;
       this.loadItems();
    }//GEN-LAST:event_btnDelCategoriaActionPerformed

    private void btnAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCategoriaActionPerformed

    private void btnBuscaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCategoriaActionPerformed
        Categoria c = (Categoria) this.controller.search();
        
        this.btnReload.setEnabled(false);
        if ( c.hashCode() == 0 ) {
            Util.showMessage("Categoria não encontrada.", "Buscador", JOptionPane.WARNING_MESSAGE );
            return ;
        }
      
        this.btnReload.setEnabled(true);
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Código");
        model.addColumn("Nome");
        model.addColumn("Descrição");
        Object[] data = {
             c.getCodigo(),
             c.getNome(),
             c.getDescricao()
         };

        model.addRow(data);
        this.tableCategoria.setModel(model);

      
    }//GEN-LAST:event_btnBuscaCategoriaActionPerformed

    private void btnReloadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReloadMouseReleased

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        this.loadItems();
        this.btnReload.setEnabled(false);
    }//GEN-LAST:event_btnReloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoria;
    private javax.swing.JButton btnBuscaCategoria;
    private javax.swing.JButton btnDelCategoria;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnReload;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextFile;
    private javax.swing.JTable tableCategoria;
    // End of variables declaration//GEN-END:variables
}
